name: date_picker
description: A new Flutter package project.
version: 0.0.2
repository: https://github.com/baseflow/flutter_date_picker

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

