name: date_picker
description: A new Flutter package project.
version: 0.1.0
repository: https://github.com/baseflow/flutter_date_picker

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
